### ISSUE TITLE
Decoded Recon mismatch for non multiple of 8 res 10bit video

### ISSUE THREAD

**Issue by hassount** [OpenVisualCloud/SVT-AV1#1225]
I did a couple of fast encodes and compared the SVT-AV1 reconstructed, SVT-AV1 decoded, and libaom decoded yuvs:
 - For 1 frame, the three outputs match
 - For 2 frames, SVT-AV1 recon & decoded match, but not libaom decoded
 - For 12 frames: the three outputs are different. 
This happened with the first two sequences picked, so I guess it is not a corner case.

Do you observe the same at your end?

_Originally posted by @joelsole in https://github.com/OpenVisualCloud/SVT-AV1/pull/1191#issuecomment-612167849_

**Comment by quietvoid** [comment]
Hi @hassount.
I'm not sure if this issue is only related to the SVT-AV1 decoder.

I'm seeing artifacts (mostly chroma related) at the bottom of non multiple of 8 resolution videos.
These kind of artifacts have been around for a while, back to at least v0.7.0.

This issue possibly targets the same bug I'm encountering so I'm not sure if a new issue should be created.
Basically, 10 bit sources with non mod 8 resolutions like 1920x804 are being encoded like this by SVT-AV1:
`SVT [config]: SourceWidth / SourceHeight                                        : 1920 / 808`

I've tested all my options and the artifacts are consistently reproducible with this simple CLI:
>.\SvtAv1EncApp.exe -i source-non-mod8.y4m --input-depth 10 --rc 0 --qp 5 --preset 4 -b out.ivf

Presets from 2-7 are affected, `preset 8` does not seem to be.

I have uploaded the source sample and an encoded file here: https://mega.nz/folder/NBkQVYwD#sAdFDs6HNP_oDideGELHjg
The artifacts are visible at the bottom of frames 1, 3, and 9.

If this isn't the right place I'll just open a new issue.

**Comment by tianjunwork** [comment]
Hi @quietvoid , I wonder if you attached the correct out.ivf file? Since I didn't see any artifacts at the bottom.
Are you using master tip? I will try it out too.

**Comment by quietvoid** [comment]
The sample uploaded is correct and I do see artifacts in there.

This is how the bottom left of frame 3 looks like zoomed in:
<img width="848" alt="frame3" src="https://user-images.githubusercontent.com/39477805/81879776-aa4ca880-9559-11ea-8950-7ee34a090994.png">

There is a green line in the image. It seems to only be present in the U and V planes, the Y plane seems to be fine.

I have updated my binaries to `v0.8.3-26-g7bdab42e-dirty` and the issue is still present.
Added that bitstream file to the MEGA folder.

**Comment by tianjunwork** [comment]
With `./SvtAv1EncApp -i source-non-mod8.y4m --input-depth 10 --rc 0 --qp 5 --preset 4 -b out.ivf`, I only got 7 output frames. Not sure about your out.ivf with 11 frames.
Any way, I tried to decode your attached out.ivf.
1. `./SvtAv1DecApp -i out.ivf -o out.yuv`, didn't observe both artifacts.
2. Also tried with libdav1d eaedb95, didn't observe both artifacts either.
```
[libdav1d @ 0000022806f2cf80] libdav1d eaedb95
Stream mapping:
  Stream #0:0 -> #0:0 (av1 (libdav1d) -> rawvideo (native))
Press [q] to stop, [?] for help
Output #0, rawvideo, to 'out.yuv':
  Metadata:
    encoder         : Lavf58.43.100
    Stream #0:0: Video: rawvideo (Y3[11][10] / 0xA0B3359), yuv420p10le, 1920x804, q=2-31, 555724 kb/s, 24 fps, 24 tbn, 24 tbc
    Metadata:
      encoder         : Lavc58.84.100 rawvideo
frame=   11 fps=0.0 q=-0.0 Lsize=   49748kB time=00:00:00.45 bitrate=889160.3kbits/s speed=0.72x
video:49748kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.000000%
```
Could you also double check with different decoders?

**Comment by quietvoid** [comment]
Hello. I am not sure why we are seeing different results.

Decoded `v0.8.3-26-g7bdab42e-dirty.ivf` with the different decoders:
>.\aomdec.exe --output-bit-depth=10 .\v0.8.3-26-g7bdab42e-dirty.ivf -o aomdec.yuv
.\dav1d.exe -i .\v0.8.3-26-g7bdab42e-dirty.ivf -o dav1d_0.6.0-95-geaedb95.yuv
.\SvtAv1DecApp.exe -i .\v0.8.3-26-g7bdab42e-dirty.ivf -o out.yuv

I have done sha256sum on the decoded files (trimmed to look nice):
>700a5a8b69961ecc819a1aa2b aomdec 18ce7a0a0.yuv
9ad77c718ecea8717b6246283 dav1d_0.6.0-95-geaedb95.yuv
9ad77c718ecea8717b6246283 svtav1decapp v0.8.3-26-g7bdab42e.yuv

They are all 11 frames long, and all exhibit the same artifacts on my side.
You can find the .yuv files here: https://mega.nz/folder/ActwwKZB#ftuOjui_VXs79XaaLL_unw

I've tried reencoding the sample file, the log is available here: https://0x0.st/iLcp.txt
Definitely also shows 11 frames.

**Comment by tianjunwork** [comment]
Using your command and input file, I did only generate 7 output frames with total 1758580 bytes.
```
(master) $ ./SvtAv1EncApp -i ../../../../yuv/source-non-mod8.y4m --input-depth 10 --rc 0 --qp 5 --preset 4 -b out.ivf
-------------------------------------------
SVT [version]:  SVT-AV1 Encoder Lib v0.8.3
SVT [build]  :  GCC 8.1.0        64 bit
LIB Build date: May 13 2020 18:06:42
-------------------------------------------
Number of logical cores available: 72
Number of PPCS 105
[asm level on system : up to avx512]
[asm level selected : up to avx2]
-------------------------------------------
SVT [config]: Main Profile      Tier (auto)     Level (auto)
SVT [config]: EncoderMode                                                       : 4
SVT [config]: EncoderBitDepth / EncoderColorFormat / CompressedTenBitFormat     : 10 / 1 / 0
SVT [config]: SourceWidth / SourceHeight                                        : 1920 / 808
SVT [config]: Fps_Numerator / Fps_Denominator / Gop Size / IntraRefreshType     : 24 / 1 / 32 / 1
SVT [config]: HierarchicalLevels  / PredStructure               : 4 / 2
SVT [config]: BRC Mode / QP  / LookaheadDistance / SceneChange                  : CQP / 5 / 33 / 0
-------------------------------------------
Encoding         7
SUMMARY --------------------------------- Channel 1  --------------------------------
Total Frames            Frame Rate              Byte Count              Bitrate
           7            24.00 fps                  1758464              48232.16 kbps


Channel 1
Average Speed:          0.997 fps
Total Encoding Time:    7024 ms
Total Execution Time:   14955 ms
Average Latency:        6185 ms
Max Latency:            7008 ms
Encoder finished
```
![image](https://user-images.githubusercontent.com/4551215/81897613-d40ecb00-956b-11ea-8d87-633171379785.png)

**Comment by tianjunwork** [comment]
Really sorry about all the confusion. I guess when I was copying the source yuv, vpn lost connection, only partial are copied to remote server. 
Now I can reproduce both artifacts. Curious how you found them? It is hard by bare eye. And psnr may not drop that much with that small artifacts?
This should count as a separate issue.

**Comment by quietvoid** [comment]
I only look at the output encoded images, not metrics.
Been playing with all the AV1 encoders for almost 2 years now and this is one of the long standing issues I keep seeing with SVT-AV1.

I will make a proper issue for this. Thank you.

**Comment by hassount** [comment]
closing this as #1302 has been addressed
