### ISSUE TITLE
Thread affinity broken on MacOS

### ISSUE THREAD

**Issue by kylophone** [OpenVisualCloud/SVT-AV1#132]
This uses some Linux specific APIs. We missed this because our build script in Travis MacOS did not properly return an error. (#127)

**Comment by kylophone** [comment]
See also: https://github.com/OpenVisualCloud/SVT-AV1/pull/130#issuecomment-468794601

**Comment by 1480c1** [comment]
Things I would like to add that need modifications for MacOS and possibly some relevant information
- MacOS fails on all SVT-* projects.
- cpu_set_t is not present.
  - <https://yyshen.github.io/2015/01/18/binding_threads_to_cores_osx.html> might help
  - pthreads on mac is not exactly the same as linux etc. ( Does not include `pthread_setaffinity_np`)
- "gcc" on apple is linked to clang and has the Cmake c compiler identifier `AppleClang`
   - There is no flags for clang set in the cmake files. ( It can be fixed by changing STREQUAL "GNU" to MATCHES "GNU|CLANG" most of the time)
  - `__attribute__((optimize("unroll-loops")))` is unknown to clang, but clang does know `#pragma clang unloop`
- `__linux__` and `__UNIX__` is not defined, however `__APPLE__` and `__CLANG__` is defined
- AVX2 needs `-mxsave` for Mac(I think)
- If yasm is installed using `brew install yasm`, it will come with GNU GCC and its tools can be accessed by appending *-8 to the end of the tools (eg gcc-8, gcc-ar-8, c++-8, etc)
  - A lot of the standard stuff doesn't work with it (mac likes to hide them in some other places)
- It's either `ar` or `libtool -static` for its ar. (Idk which it actually is)
  - For the CMakeLists, it can use `CMAKE_AR="libtool"` and `CMAKE_C_ARCHIVE_CREATE "<CMAKE_AR> -static -o <TARGET> <LINK_FLAGS> <OBJECTS>"`
  - There is no gcc-ranlib other than the gcc-ranlib-8, but it does have `ranlib`

I've tried some of the stuff on SVT-HEVC, and in the end I got <https://travis-ci.org/1480c1/SVT-HEVC/jobs/500489963#L454>
```
[ 94%] Linking C shared library ../../../../Bin/Release/libSvtHevcEnc.dylib
Undefined symbols for architecture x86_64:
  "_GatherSaoStatisticsLcu16bit_SSE2", referenced from:
      _SaoGatherFunctionTabl_16bit in EbSampleAdaptiveOffsetGenerationDecision.c.o
  "_Log2f_SSE2", referenced from:
      _EncDecKernel in EbEncDecProcess.c.o
      _EntropyCodingKernel in EbEntropyCodingProcess.c.o
      _FillAMVPCandidates in EbAdaptiveMotionVectorPrediction.c.o
      _EncodePass in EbCodingLoop.c.o
      _LargestCodingUnitCtor in EbCodingUnit.c.o
      _PmEstimateQuantCoeffLuma_SSE2 in EbCoeffEstimation_Intrinsic.c.o
      _PmEstimateQuantCoeffChroma_SSE2 in EbCoeffEstimation_Intrinsic.c.o
      ...
  "_PictureCopyKernel_SSE2", referenced from:
      _AvcStyleCopy_SSE2 in libASM_SSE2.a(EbAvcStyleMcp_Intrinsic_SSE2.c.o)
      _LumaInterpolationCopy16bit_SSE2 in libASM_SSE2.a(EbMcp_Intrinsic_SSE2.c.o)
      _ChromaInterpolationCopy16bit_SSE2 in libASM_SSE2.a(EbMcp_Intrinsic_SSE2.c.o)
  "_ZeroOutCoeff16x16_SSE2", referenced from:
      _PicZeroOutCoef_funcPtrArray in EbTransforms.c.o
  "_ZeroOutCoeff32x32_SSE2", referenced from:
      _PicZeroOutCoef_funcPtrArray in EbTransforms.c.o
  "_ZeroOutCoeff4x4_SSE", referenced from:
      _PicZeroOutCoef_funcPtrArray in EbTransforms.c.o
  "_ZeroOutCoeff8x8_SSE2", referenced from:
      _PicZeroOutCoef_funcPtrArray in EbTransforms.c.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

You can probably ignore what I did since most of my S tier patches (S meaning shiitake) are from a guy who's never done a Hello World in C and whose knowledge of C comes from 1 week of looking at stackoverflow and other documents. Plus, they come from SVT-HEVC, not AV1.

**Comment by 1480c1** [comment]
If anyone wants to see the actual headers or if mac has a certain file or lib, I have access to a macbook pro(My sister's) with High Sierra on it and can possibly send information.

**Comment by 1480c1** [comment]
One thing I noticed about some of the undefined symbols is that most of them are from the asm files and are prefixed by the cglobal macro such as the ZeroOutCoeff* and the zero_out_coef* from <https://travis-ci.com/OpenVisualCloud/SVT-AV1/jobs/181432561#L301>

**Comment by 1480c1** [comment]
<https://stackoverflow.com/a/10145363/10498220>
It seems that clang on macOS prefixes with _ and yasm doesn't, so the code looks for `_ZeroOutCoeff4x4_SSE` but the asm has `ZeroOutCoeff4x4_SSE`
