### ISSUE TITLE
master / svt-01 branches synch

### ISSUE THREAD

**Issue by hassount** [OpenVisualCloud/SVT-AV1#1389]
As work in the svt-01 branch has diverged quite a bit from master due to the need of doing some research work / restructuring into MD, the svt-01 branch is being manually rebased on top of master in order for it to be merged. This issue is to track progress and synchronize PRs as merging the branch is a major change.

FYI, this would probably need a small freeze to master

**Comment by ccccheung** [comment]
We have run some stability tests over this branch and ran guitar_hdr_amazon1080p due to known R2R issues with that clip. However, the encoding did not run because of the following Error: "Error instance 1: Invalid HBD mode decision flag [-1 - 2], your input: 255".

This is likely due to a new default of -1 being set for the parameter enable_hbd_mode_decision. However, the type of this is uint8_t as declared in EbSvtAv1Enc.h line 429
