### ISSUE TITLE
Frame rate should always be expressed as a rational

### ISSUE THREAD

**Issue by kylophone** [OpenVisualCloud/SVT-AV1#140]
Right now there is `cfg->frameRate`, `cfg->frameRateNumerator`, `cfg->frameRateDenominator`.

Why is `frameRate` expressed in this way?

**Comment by hassount** [comment]
@kylophone 
we don't need all 3 of them. basically if the fps is an integer, then we can use cfg->frameRate otherwise,
we would use cfg->frameRateNumerator, cfg->frameRateDenominator. 
I personally find it easier in the cmd to enter -fps 60 instead of typing -fps-num 60000 -fps-denom 1000.
ultimately everything is written in the bitstream as a num - denom pair. 
Is there a problem to keep both ways ?

**Comment by kylophone** [comment]
It's not ideal to express the same thing twice. Things could get out of sync, and there's extra checking code needed each the field needs to be accessed. Also only a rational can accurately express a non-integer frame rate.

**Comment by hassount** [comment]
can we close this issue keeping all options ?
