### ISSUE TITLE
Error on FFmpeg patch

### ISSUE THREAD

**Issue by EwoutH** [OpenVisualCloud/SVT-AV1#15]
I got this error when trying to compile the FFmpeg patch.

- Compile commands: https://github.com/EwoutH/SVT-AV1/blob/248f8486e93f8259093b57437f33bf8b3f882d85/.travis.yml
- Full log: https://travis-ci.com/EwoutH/SVT-AV1/jobs/175239496#L2588

```
CC	libavcodec/libsvt_av1.o
libavcodec/libsvt_av1.c: In function ‘config_enc_params’:
libavcodec/libsvt_av1.c:200:14: error: ‘EbSvtAv1EncConfiguration {aka struct EbSvtAv1EncConfiguration}’ has no member named ‘video_usability_info’
         param->video_usability_info = svt_enc->vui_info;
              ^
libavcodec/libsvt_av1.c: In function ‘eb_enc_init’:
libavcodec/libsvt_av1.c:303:1: warning: label ‘failed_init_enc’ defined but not used [-Wunused-label]
 failed_init_enc:
 ^
ffbuild/common.mak:60: recipe for target 'libavcodec/libsvt_av1.o' failed
make: *** [libavcodec/libsvt_av1.o] Error 1
make: *** Waiting for unfinished jobs....
The command "make -j `nproc`" exited with 2.
```

**Comment by vannan-mani** [comment]
Have the same problem, since this was usability information, commented the above, plugin compiles and installs correctly. 
On initialization comes up with an arithmetic failure. Attached the debugger logs

I did try the patch against the latest ffmpeg on the trunk and the patch had no compilations. There was a problem with non-available member as below
 /*    if (svt_enc->vui_info)
    200         param->video_usability_info = svt_enc->vui_info;
    201 */

since this was regarding video usability information, i decided to comment this out and the ffmpeg code compiled and launched.

now on a simple encode, the plugin throws up a floating point exception and coredumps
 ffmpeg  -i pt.mov -c:v libsvt_av1 -y pt_av1.mp4
ffmpeg version N-93075-gb429c86 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.3.0-27ubuntu1~18.04)
  configuration: --prefix=/home/pas/ffmpeg_build --pkg-config-flags=--static --extra-cflags=-I/home/pas/ffmpeg_build/include --extra-ldflags=-L/home/pas/ffmpeg_build/lib --extra-libs='-lpthread -lm' --bindir=/home/pas/bin --enable-gpl --enable-libaom --enable-libass --enable-libfdk-aac --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-nonfree --enable-libsvtav1
  libavutil      56. 26.100 / 56. 26.100
  libavcodec     58. 46.100 / 58. 46.100
  libavformat    58. 26.100 / 58. 26.100
  libavdevice    58.  6.101 / 58.  6.101
  libavfilter     7. 48.100 /  7. 48.100
  libswscale      5.  4.100 /  5.  4.100
  libswresample   3.  4.100 /  3.  4.100
  libpostproc    55.  4.100 / 55.  4.100
Guessed Channel Layout for Input Stream #0.1 : stereo
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'pt.mov':
  Metadata:
    major_brand     : qt 
    minor_version   : 537199360
    compatible_brands: qt 
    creation_time   : 2015-07-16T12:50:24.000000Z
  Duration: 00:02:58.83, start: 0.000000, bitrate: 112062 kb/s
    Stream #0:0(eng): Video: prores (Standard) (apcn / 0x6E637061), yuv422p10le(tv, bt709, progressive), 1920x1080, 110507 kb/s, SAR 1:1 DAR 16:9, 24 fps, 24 tbr, 24 tbn, 24 tbc (default)
    Metadata:
      creation_time   : 2015-07-16T12:50:24.000000Z
      handler_name    : Apple Video Media Handler
      encoder         : Apple ProRes 422
      timecode        : 04:16:55:14
    Stream #0:1(eng): Audio: pcm_s16le (sowt / 0x74776F73), 48000 Hz, stereo, s16, 1536 kb/s (default)
    Metadata:
      creation_time   : 2015-07-16T12:50:24.000000Z
      handler_name    : Apple Sound Media Handler
    Stream #0:2(eng): Data: none (tmcd / 0x64636D74) (default)
    Metadata:
      creation_time   : 2015-07-16T12:51:46.000000Z
      handler_name    : Time Code Media Handler
      timecode        : 04:16:55:14
Stream mapping:
  Stream #0:0 -> #0:0 (prores (native) -> av1 (libsvt_av1))
  Stream #0:1 -> #0:1 (pcm_s16le (native) -> aac (native))
Press [q] to stop, [?] for help
SVT [version]:    SVT-AV1 Encoder Lib v0.4.0
SVT [build]  :    GCC 7.3.0     64 bit
LIB Build date: Feb  4 2019 13:59:50
-------------------------------------------
Number of logical cores available: 12
Number of PPCS 53
-------------------------------------------
SVT [config]: Main Profile    Tier (auto)    Level (auto)   
SVT [config]: EncoderMode                             : 1
SVT [config]: EncoderBitDepth / CompressedTenBitFormat                : 8 / 0
SVT [config]: SourceWidth / SourceHeight                    : 1920 / 1080
SVT [config]: Fps_Numerator / Fps_Denominator / Gop Size / IntraRefreshType     : 24 / 1 / 12 / 1
SVT [config]: HierarchicalLevels / BaseLayerSwitchMode / PredStructure        : 3 / 0 / 2
SVT [config]: BRC Mode / QP  / LookaheadDistance / SceneChange            : CQP / 32 / 17 / 0
-------------------------------------------
Floating point exception (core dumped)


digging further into the core dump, i found the following

Thread 1 "ffmpeg" received signal SIGFPE, Arithmetic exception.
0x0000555556a6bbf4 in av1_alloc_restoration_struct ()
(gdb) bt
#0  0x0000555556a6bbf4 in av1_alloc_restoration_struct ()
#1  0x0000555556a0e620 in av1_alloc_restoration_buffers ()
#2  0x00007ffff44007d1 in PictureParentControlSetCtor () from /usr/local/lib/libSvtAv1Enc.so
#3  0x00007ffff4423123 in EbSystemResourceCtor () from /usr/local/lib/libSvtAv1Enc.so
#4  0x00007ffff43a004d in eb_init_encoder () from /usr/local/lib/libSvtAv1Enc.so
#5  0x00005555556a69ba in ?? ()
#6  0x0000555555e11e86 in ?? ()
#7  0x000055555571cfb4 in ?? ()
#8  0x000055555571ee59 in ?? ()
#9  0x0000555555722bb4 in ?? ()
#10 0x00005555556ff4ae in ?? ()
#11 0x00007ffff2944b97 in __libc_start_main (main=0x5555556ff370, argc=7, argv=0x7fffffffdf78, init=<optimized out>,
    fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffdf68) at ../csu/libc-start.c:310
#12 0x00005555556ff8ca in ?? ()

Have used the release versions on both ffmpeg and the libsvt-av1, will dig into the debug versions and send further information.

In the meanwhile, if somebody knows what this is, please let me know

Best Regards

**Comment by EwoutH** [comment]
@vannan-mani Can you start and end a code block with ``` ? Now it references to all open issues.
```
lines
with
code
```

**Comment by vannan-mani** [comment]
> @vannan-mani Can you start and end a code block with ``` ? Now it references to all open issues.
> 
> ```
> lines
> with
> code
> ```

Have edited, hope that stops it. 
Apologies for the trouble.

**Comment by kylophone** [comment]
@hassount, can you tag the author of the FFmpeg patch to this? I'm not sure who that is. Our Travis build is failing because this patch doesn't apply anymore.

**Comment by hassount** [comment]
@kylophone 
Working on it. 
as for the the patch, it is usually applicable to a tag and it will be very challenging to keep updating it every time there's an update, does that make sense ?

**Comment by hassount** [comment]
@EwoutH 
Can we close this issue ?
