### ISSUE TITLE
[SVT AV1]No error print when do negative test of parameters "-fps", "-q" and "-pred-struct" with master code ad4522f

### ISSUE THREAD

**Issue by liweki** [OpenVisualCloud/SVT-AV1#250]
Use the latest code with commit ID ad4522f to do negative test, found there is no error print for parameters "-fps", "-q" and "-pred-struct".

Test command we used like below:
1. encoders/SvtAv1EncApp -w 1920  -h 1080  -i ./yuvs/BasketballDrive_1920x1080_50.yuv  **-pred-struct 15** -n 5
2. encoders/SvtAv1EncApp -w 1920  -h 1080  -i ./yuvs//BasketballDrive_1920x1080_50.yuv  **-fps 9223372036854775849** -n 5
3. encoders/SvtAv1EncApp -w 1920  -h 1080  -i ./yuvs/BasketballDrive_1920x1080_50.yuv  **-q -20** -n 5

**Comment by JackZhouVCD** [comment]
A few quick notes I have on this:

> 1. encoders/SvtAv1EncApp -w 1920  -h 1080  -i ./yuvs/BasketballDrive_1920x1080_50.yuv  **-pred-struct 15** -n 5

 - `-pred-struct` is actually [hardcoded](https://github.com/OpenVisualCloud/SVT-AV1/blob/ad4522fb9fa4498363a58af12edb432a5c0642e1/Source/Lib/Encoder/Codec/EbEncHandle.c#L2244) right now to be 2

> 2. encoders/SvtAv1EncApp -w 1920  -h 1080  -i ./yuvs//BasketballDrive_1920x1080_50.yuv  **-fps 9223372036854775849** -n 5

 - As of d8c5bc2 giving an illegal value for `-fps` yields the correct error print and exits the encoder

> 3. encoders/SvtAv1EncApp -w 1920  -h 1080  -i ./yuvs/BasketballDrive_1920x1080_50.yuv  **-q -20** -n 5

 - The encoder continues to encode with an illegal qp value because the encoder verifies settings in scs.static_config. In our case the illegal qp value is written to scs->qp, but scs->static_config.qp contains a different value.

I also found that giving an illegal value for `-lad` also has the same issue (there maybe more, I just haven't seem them yet), and this is because the value of `-lad` is automatically capped to an appropriate value. There may be something we can do to the app to make this more clear to an end user. @hassount thoughts?
