### ISSUE TITLE
Add support for static library build

### ISSUE THREAD

**Issue by tmatth** [OpenVisualCloud/SVT-AV1#39]
Currently it seems that the library is hardcoded to build a .so.

**Comment by bleunova** [comment]
Yes, I like to know how to build static library. Any help would be appreciated.

**Comment by jstebbins** [comment]
Hi all.  I'm looking into adding static lib support.  I basically have it working, but there are duplicate symbols in the App and the lib that case final link to fail (symbols are str\*_ss, EbStartTime and EbFinishTime). They are duplicated because the shared lib doesn't export them, and they are needed in the App.  

I'm wondering if these things should become part of the library's exported API or if you would prefer to keep them separate and just de-duplicate by changing function names?  The str\*_ss functions appear to be currently only used in the App even though the functions are duplicated in the lib.  EbStartTime and EbFinishTime are used in both the App and the lib.

FYI, I was also able to coax it into building with mingw with a few small changes.

**Comment by kylophone** [comment]
Hi,
> Hi all. I'm looking into adding static lib support. I basically have it working, but there are duplicate symbols in the App and the lib that cause final link to fail (symbols are str*_ss, EbStartTime and EbFinishTime). They are duplicated because the shared lib doesn't export them, and they are needed in the App.
> 
> I'm wondering if these things should become part of the library's exported API or if you would prefer to keep them separate and just de-duplicate by changing function names? The str*_ss functions appear to be currently only used in the App even though the functions are duplicated in the lib. EbStartTime and EbFinishTime are used in both the App and the lib.

 I wonder if we could somehow do without those functions is the app. They're not part of the encoding API, so they should not be exported.  I think the string functions are mostly used for parsing the command line options (iirc), which could/should be replaced with something like `getopt.h`. There are shell built-ins for time on most platforms, so that might be OK to axe as well. I'll let others chime in.

> 
> FYI, I was also able to coax it into building with mingw with a few small changes.

Ah, great. Let me know If you get that going, It would be nice to have it in Travis.

Thanks,
Kyle

**Comment by jstebbins** [comment]
For now, I've stripped those function definitions from App and exported them from the lib so that App can use them.  If the decision is to also strip their usage from App, it would be a simple thing to un-export these functions.

**Comment by jstebbins** [comment]
I submitted a PR for adding static library build support.  MinGW build support is also working, see https://github.com/jstebbins/SVT-AV1/tree/mingw. It's built on top of the static lib PR, so I'll hold off on submitting that until the static lib PR is reviewed and accepted.

**Comment by zhongyizengzy** [comment]
this branch can be merge into master?

**Comment by 1480c1** [comment]
This can probably be closed

**Comment by tmatth** [comment]
Fixed in #67
