### ISSUE TITLE
Recon yuvs do not match with decoded yuv

### ISSUE THREAD

**Issue by Cidana-Developers** [OpenVisualCloud/SVT-AV1#392]
version: c2df2c75b8c10214a1080fce49ff2a787938ed54
platform: mac
How to reproduce:
build:
`./build.sh release`
encode with recon enabled:
`./SvtAv1EncApp -i ~/work/tempete_cif.y4m -b output.ivf -o tempete_recon.yuv -n 30 -enc-mode 8`
decode the ivf with aomdec:
`./aomdec --i420 --rawvideo -o aom_output.yuv --summary --output-bit-depth=8 output.ivf`

Result:
aom_output.yuv is different with tempete_recon.yuv. 
md5 of aom_output.yuv: 065d051cea865e33aa44b02dcc612516
md5 of tempete_recon.yuv: efc239ff44f72be3835a7f62f0e901d8
Expected:
aom_output.yuv should be the same as tempete_recon.yuv.

**Comment by digitalTrilunaire** [comment]
Maybe I'm wrong but I think what your missing here is the playback with ffmpeg or/and extraction with aom.
Maybe your _tempete_recon.yuv_, the output of svtEncApp is in i420. FFmpeg read correctly the first one, because by default it read the i420 pixel format. Your other video is in yv12, and ffmpeg try to read it as an i420. When I tried to play and yv12 pixel format video with ffmpeg, I experience the same chroma shift that you experienced (as you can see below), it is because of the chanel order: i420=y->u->v and yv12=y->v->u.
What you can add to your test is the `/aomdec --i420 --rawvideo -o aom_output.yuv --summary --output-bit-depth=8 output.ivf` and retry with ffmpeg and compare the two MD5.
![yv12 read as an i420](https://user-images.githubusercontent.com/31803439/59697614-76082500-91ee-11e9-8d07-d0a710c37add.png)
![i420](https://user-images.githubusercontent.com/31803439/59697615-76a0bb80-91ee-11e9-9f82-3dbc07d1c1a3.png)

**Comment by Cidana-Developers** [comment]
> Maybe I'm wrong but I think what your missing here is the playback with ffmpeg or/and extraction with aom.
> Maybe your _tempete_recon.yuv_, the output of svtEncApp is in i420. FFmpeg read correctly the first one, because by default it read the i420 pixel format. Your other video is in yv12, and ffmpeg try to read it as an i420. When I tried to play and yv12 pixel format video with ffmpeg, I experience the same chroma shift that you experienced (as you can see below), it is because of the chanel order: i420=y->u->v and yv12=y->v->u.
> What you can add to your test is the `/aomdec --i420 --rawvideo -o aom_output.yuv --summary --output-bit-depth=8 output.ivf` and retry with ffmpeg and compare the two MD5.
> ![yv12 read as an i420](https://user-images.githubusercontent.com/31803439/59697614-76082500-91ee-11e9-8d07-d0a710c37add.png)
> ![i420](https://user-images.githubusercontent.com/31803439/59697615-76a0bb80-91ee-11e9-9f82-3dbc07d1c1a3.png)

updated, thanks.

**Comment by Cidana-Developers** [comment]
@digitalTrilunaire updated the issue, thanks.

**Comment by digitalTrilunaire** [comment]
Ok thanks, @Cidana-Developers. Do you still experience the chroma shift with the ffmpeg playback?

**Comment by Cidana-Developers** [comment]
> Ok thanks, @Cidana-Developers. Do you still experience the chroma shift with the ffmpeg playback?

No, it works fine.

**Comment by hassount** [comment]
Can we close this ?

**Comment by Cidana-Developers** [comment]
@hassount I tried 9e67b31961c59166cbeca85b9838061607c9ad09, the reconstructed yuv from encoder still does not match with decoded yuv from aom decoder.
MD5 (aom_output.yuv) = 8728a6b8ea545e76f85db9e134bc84c3
MD5 (tempete_recon.yuv) = f700ea0d6a1efc371e7f26c26df2f76b

**Comment by digitalTrilunaire** [comment]
@Cidana-Developers , just a test to eliminate a possible aom config bug when you build it (e.g there were a bug with the cmake config option DCONFIG_ALLOW_LOWBITDEPTH leading to different MD5 values for the same encoding): can you decode your ivf with [dav1d](https://code.videolan.org/videolan/dav1d) and compare the three md5 values of your three yuvs (e.g with md5sum)?

**Comment by Cidana-Developers** [comment]
@digitalTrilunaire the md5 of the decoded yuv from dav1d is the same with md5 from aom decoder. Meantime this issue is fixed by 396e3e58c335a55a2799b1de12407fae515ce03f, and can be closed now.
