### ISSUE TITLE
SVT-AV1 and libaom have conflicting symbols

### ISSUE THREAD

**Issue by kylophone** [OpenVisualCloud/SVT-AV1#453]
Not tested by myself (but I'm not surprised if this is true), brought up here: http://ffmpeg.org/pipermail/ffmpeg-devel/2019-July/246504.html

> e.g : SVT-AV1 reused libaom. If you enable both libsvt-av1 and libaom as static link, then will have name conflict. 
  Such issue is not easily found if you keep wrapper patch on https://github.com/OpenVisualCloud/SVT-AV1/tree/master/ffmpeg_plugin ,
  But will easily found if works on FFmpeg mainline.

**Comment by xuguangxin** [comment]
@kylophone yes, we have this issue. I found this issue too in 3 months ago. I expect someone will clean up it someday. But seems no one notice it. 
After https://github.com/OpenVisualCloud/SVT-AV1/pull/286 this PR, I think we are ready to upstream to ffmpeg. 

I fully agree with zhong's comments. Address all concerns from the community and upstream it as early as possible will save you time, not cost your time. 
Many issues can't find internally, because intenral people always test it /see the code in the old way. The community will test and see it in a different way.

Another good example is the interface. Currently svt [hevc](https://github.com/OpenVisualCloud/SVT-HEVC/blob/master/ffmpeg_plugin/0001-lavc-svt_hevc-add-libsvt-hevc-encoder-wrapper.patch#L344), [vp9](https://github.com/OpenVisualCloud/SVT-VP9/blob/master/ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-vp9.patch#L333), [av1](https://github.com/OpenVisualCloud/SVT-AV1/blob/master/ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-av1-with-svt-hevc.patch#L332) has totally different API name. So you have to write 3 plugins for them. Some bug fixed in av1 like https://github.com/OpenVisualCloud/SVT-AV1/pull/286 will not fixed [vp9](https://github.com/OpenVisualCloud/SVT-VP9/blob/master/ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-vp9.patch#L345). vice versa. 
If you upstream to the community, the community will tell you refact your interface let the plugin share 95% of the code, it will save you much time.
thanks

**Comment by jsunintel** [comment]
That's a known issue: https://github.com/OpenVisualCloud/SVT-AV1/issues/119, which was submitted by me at Feb. Please look into it.

**Comment by xuguangxin** [comment]
@jsunintel , little confused about this. 
The issues closed at Feb. But I found this issue at 28th, March. 
Are you sure the latest code has no such issue?
thanks

**Comment by jsunintel** [comment]
> 
> 
> @jsunintel , little confused about this.
> The issues closed at Feb. But I found this issue at 28th, March.
> Are you sure the latest code has no such issue?
> thanks

First, a patch to SVT-AV1 is required, which is already merged. Second, you need to make a change to libaom and build it as a shared library, but not a static one. The config option exists but not set by default.

If it's a static library, its global symbols are visiable to all. Since the two share global symbol names, building them as shared is required.

**Comment by xuguangxin** [comment]
HI @jsunintel ,
Change libaom default link type is a workaround, not a fix. People will continue face same problem since libaom default configuration is a static link. We can't expect user find the issue, dig into details and find the workaround.
Is it possible to add some prefixes to libaom functions in SVT AV1?

thanks

**Comment by jsunintel** [comment]
> 
> 
> HI @jsunintel ,
> Change libaom default link type is a workaround, not a fix. People will continue face same problem since libaom default configuration is a static link. We can't expect user find the issue, dig into details and find the workaround.
> Is it possible to add some prefixes to libaom functions in SVT AV1?
> 
> thanks

My solution is offered in GitHub page and it works well.

There are thousands of duplicated symbol names. I have talked with @hassount, and they did not like the renaming idea.  You would double check with them.

**Comment by xuguangxin** [comment]
@hassount @jsunintel , is it possible to use some regex to replace the variables?

If @kylophone did not find the original issue in the first time, how we expect other people can find the workaround?

**Comment by jsunintel** [comment]
> 
> 
> @hassount @jsunintel , is it possible to use some regex to replace the variables?
> 
> If @kylophone did not find the original issue in the first place, how we expect other people can find the workaround?

It is here in the GitHub, not hidden or anything. And when an issue was submitted for it, even I did not got @. I responed with the the answer.
