### ISSUE TITLE
[SVT_AV1] Open Dev Meeting

### ISSUE THREAD

**Issue by hassount** [OpenVisualCloud/SVT-AV1#811]
Organizing an open meeting where all developers and contributors to svt-av1 can join. This is an opportunity for everyone to ask any questions about the roadmap and or make / agree on any suggestions to improve the development and contribution process.

When: Suggesting Wednesday Nov27th @ 8:30 - 9:30 am PST
Where: [conference link](meet.google.com/rty-mkxi-wvi) [more info](https://github.com/OpenVisualCloud/SVT-AV1/issues/811#issuecomment-558856084)
Agenda: open to suggestions from the community

**Comment by 1480c1** [comment]
Couple of things I think would be good to discuss

- Sample app design (https://github.com/OpenVisualCloud/SVT-AV1/issues/779)
  - Maybe consider using a C++ sample app and C library since we already require a C++ compiler (Although it's only used for Unit Tests atm) and it may be more convenient to write an application in C++ than pure C.
- Clean up globals and exports (https://github.com/OpenVisualCloud/SVT-AV1/issues/572 and https://github.com/OpenVisualCloud/SVT-AV1/issues/668#issuecomment-542888807)
  - Check what are marked as extern and globals and maybe reduce the amount of export headers to `EbSvtAv1Enc.h` `EbSvtAv1Dec.h` only to reduce confusion on which headers are actually needed to be included
- In line with cleanup, conflicts between other popular libs that people might build with ffmpeg (https://github.com/OpenVisualCloud/SVT-AV1/issues/567, https://github.com/OpenVisualCloud/SVT-AV1/issues/259, and https://github.com/OpenVisualCloud/SVT-AV1/issues/73)

Also, you probably should've added a space between `@8` since now you pinged a person whose username is `8`

**Comment by kylophone** [comment]
> #779 

+1

**Comment by kylophone** [comment]
> Where: Some conference bridge [TBD]

If you prefer to ask questions via IRC at this time, that should be fine too.

**Comment by grill05** [comment]
> > #779
> 
> +1

In general, I agree that the command-line app can have a better interface. That being said, since there is development time, it might be worth considering as to whether lots of users will actually use the command-line app once the ffmpeg interface becomes stable.

For example, people rarely use x264/x265 these days via the command-line program, since its so much easier to use the libs via ffmpeg. I suppose at some point the svt-av1 ffmpeg plugin will allow passing arbitrary params to libSvtEnc (via something  like --svt-params maybe, following the convention of --x265-params and --rav1e-params in ffmpeg). Once that happens, and most distros and static ffmpeg builds (zeranoe/jvansickle etc) start including libsvt-av1, there will be little incentive to use SvtAv1EncApp IMO

**Comment by andrey-norkin** [comment]
Please find the meeting info below: 

Join Hangouts Meet
meet.google.com/rty-mkxi-wvi

Meeting ID
https://meet.google.com/rty-mkxi-wvi?hs=122

Phone Numbers
(‪US‬)  +1 929-269-1840‬
PIN: ‪542 747#‬

More phone numbers
https://meet.google.com/tel/rty-mkxi-wvi?pin=9055644317111&hs=1

**Comment by kylophone** [comment]
I'll keep an eye on `#svt` on freenode as well.

**Comment by 1480c1** [comment]
@EwoutH, does `#svt` have a logbot of some kind?

**Comment by kylophone** [comment]
No

> @EwoutH, does `#svt` have a logbot of some kind?

Not that I'm aware of. I should have a local log that I can share for the time of the meeting.

**Comment by 1480c1** [comment]
That would be good, I'm not very well setup to interact with irc.

I should probably setup some kind of irc client on a server to ssh to instead of using the web client some time

**Comment by EwoutH** [comment]
@hassount Thanks for setting this up! A little busy, but I will try to make it.

@1480c1 @kylophone Good suggestion, `#svt` is now [logged](https://freenode.logbot.info/svt) with LogBot.

@1480c1 We should look into disabling CI if only the documentation is changed.

**Comment by 1480c1** [comment]
Afaik, Travis only has https://docs.travis-ci.com/user/customizing-the-build/#skipping-a-build

**Comment by hassount** [comment]
Thank you all for dialing in today.

Next meeting tentative date: January 8th 2020, @ 8:30 - 9:30 am PST

**Comment by kylophone** [comment]
Lost the Hangouts chat log when I exited the call :( but I'm working on trying to retrieve those. IRC logs are available here: https://freenode.logbot.info/svt/20191127. There is also an audio recording for a good portion of the call available. See: https://freenode.logbot.info/svt/20191127#c2909571-c2909573. 

Topics covered were as follows (I still need to fill out the notes). If I missed something, feel free to let me know. 

> (Ewout) How many coding tools are left? 10 bit?
> Ewout - About the regression on videocodectracker. 10 bit regression.
> Pipe
> Sample app
> Two pass?
> Speed settings. Presets. x264 like matrix. Issue #51.
> API, is it stable? When will it be stable. 6 months.
> Trello? Can we depricate it. Github projects?
> Frequency 1 month. Starting the first week of January.
> Quantization scaling. Two pass block level block quantization.

**Comment by EwoutH** [comment]
@kylophone #52 ;)

**Comment by kylophone** [comment]
> @kylophone #52 ;)

Fixed. Thanks.

**Comment by hassount** [comment]
New issue #932
