### ISSUE TITLE
videocodectracker.dev : regarding "Timing is not accurate"

### ISSUE THREAD

**Issue by grill05** [OpenVisualCloud/SVT-AV1#886]
Its great that two new graphs for encoding speeds have been added to https://videocodectracker.dev. Assuming that those data-points are generated on an AWS instance, normalizing with a reference (chosen to be 2019/12/03 ) seems correct.
But, post-normalization, the data (change in normalized encoding time) should be accurate. So why is it said in the header that " Timing is not accurate" ?

P.S. I use a variant of this approach (normalizing with respect to a reference) for [my own, very basic, liboam tracker]( http://thorondor.atwebpages.com). I run fresh encodes with the latest ffmpeg+libaom, and normalize them using the speed data generated with a "baseline" ffmpeg+liboam binary. I run on a GCP instance, but I've found the normalized speed data to be fairly accurate usually. 
If this has something to do with scaling, could the encoding-speed test be run with `-lp 1` maybe..

**Comment by joelsole** [comment]
I agree that the note stating 'timing is not accurate' might need some further qualification.  

Encoding time accurate enough to be a good indicator of the trend. So in that sense, the graphs are useful and that's why they have been added. However, the encoding time is not accurate enough to measure small changes introduced by some commits, as the variance of the measurement error might be larger than the signal. And that's why the 'timing is not accurate' note was put there. 

If you have a suggestion on how to word it, we can update the note in the tracker.

**Comment by grill05** [comment]
> However, the encoding time is not accurate enough to measure small changes introduced by some commits, as the variance of the measurement error might be larger than the signal

That seems reasonable. I wonder if this effect can be shown more clearly (visually) by using error-bars (to show margin of error) ?

Also, are the vdeocodectracker.dev graphs planned to be updated on a per-commit  basis? That would seem to require a lot of cpu-cycles..

**Comment by joelsole** [comment]
It would be nice to have finer granularity, but for now, we can only do regtests on a daily basis.

**Comment by joelsole** [comment]
The note on timing has been refined according to the discussion above to:
"Relative encoding times vs reference on 2019/12/03 for enc-mode 0 (timing is accurate enough to assess the overall trend)"

Closing this.
